### ISSUE TITLE
Unresponsive after RDC

### ISSUE THREAD

**Issue by ThisIsABug** [Belphemur/SoundSwitch#112]
My machine runs mostly 24/7 (Win7 x64) and SoundSwitch does it's job very well UNTIL I connect to my machine from the outside through Windows Remote Desktop. At that point the programs windows are not callable anymore. I can see the Systray-Icon, the process is running normal (no high cpu or memory issues), I can open the Context-Menu through right-clicking the icon BUT no windows will open when I click on an entry in the Context-Menu. The configured Hotkey doesn't work anymore too (no baloon error, nothing, no response).

When I come back home SoundSwitch stays in this state. After I kill the process and start it again it works as expected.
This issue is reproduceable on my machine, every time.

When I kill/restart the process again through the Remote Desktop Connection it works also again and is fully responsive. Just that it gives me a warning: "SoundSwitch: Configuration needed. No devices available to switch to." Which is totally ok for me. After killing this RDC and opening it again SoundSwitch still works (in terms of responsiveness, there are still no devices available to switch to but that is no problem). At this state I cannot tell when Soundswitch gets unresponsive again,  I have to look into that at another point.

**Comment by Belphemur** [comment]
Hello @ThisIsABug,
(Just for the joke, nope it's a feature)

Anyway, I remember this bug, it's linked the underlying library that has some difficulty to deal with RDC. If I'm right when you start RDC, Windows do some change in the audio device to be able to move the sound from the remote computer to the controller.

It must be linked to the cache I implemented, I should remove it and try again.

**Comment by Belphemur** [comment]
@ThisIsABug Can you test the new Beta to see if this is resolved ?

**Comment by ThisIsABug** [comment]
i will ... over the next days

**Comment by ThisIsABug** [comment]
tried it with 3.11.0.32914, still the same (tested it 2 days) :(

**Comment by ThisIsABug** [comment]
@Belphemur 
Still the same issue :(

**Comment by Belphemur** [comment]
I'll have to test it myself when I have the time.

I do have some idea, but no time to work on this.

**Comment by ThisIsABug** [comment]
3.12.0.33528 fixes the problem for the most part. The program is responding and callable which is a HUGE step forward.
One little issue remains, the baloon messages do not apear anymore, but since my devices (in most cases) have different volume levels i can still see the devices change by looking at the windows-audio-volume-systray-icon :)
:+1:

**Comment by Belphemur** [comment]
What happens when you go to settings ?

Can you screenshot the device list ?

**Comment by ThisIsABug** [comment]
Now that you're asking for it I have to retract my statement :(
The UI is responsive and the switching is working but I cannot open the settings window :(
Oh damn! After I try to click on the context menu a second time it doesn't open also.
So I have to go back to the original statement of this issue, sry (device switching is still working thought).

**Comment by Belphemur** [comment]
It might be possible that this issue is also resolved in the latest release.

**Comment by ThisIsABug** [comment]
I will continue testing.

**Comment by Belphemur** [comment]
I'm closing this again.

Feel free to reopen it if needed.
